mod add;
mod completions;
mod config;
mod init;
mod list;
mod man;
mod path;
mod remove;
mod schema;
mod switch;
mod trust;
mod trust_check;
mod untrust;

pub(crate) use add::run as add;
pub(crate) use completions::run as completions;
pub(crate) use config::run as config;
pub(crate) use init::run as init;
pub(crate) use list::run as list;
pub(crate) use man::run as man;
pub(crate) use path::run as path;
pub(crate) use remove::run as remove;
pub(crate) use schema::run as schema;
pub(crate) use switch::run as switch;
pub(crate) use trust::run as trust;
pub(crate) use untrust::run as untrust;
